config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'boards#index'
  post '/', to: 'boards#create'
  get '/game/:id', to: 'boards#show', as: :game

  get '/signup', to: 'users#new', as: :sign_up
  post '/signup', to: 'users#create'

  get '/login', to: 'sessions#new', as: :log_in
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy', as: :logout

  mount ActionCable.server => '/cable'
end

app/models/application_record.rb
# frozen_string_literal: true

# Application record
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/board.rb
# frozen_string_literal: true

# Class for modeling boards
class Board < ApplicationRecord
end

app/models/user.rb
# frozen_string_literal: true

# Class for modeling users
class User < ApplicationRecord
  attr_accessor :password_confirmation
  validates :username, presence: true, length: { maximum: 15 }, uniqueness: true
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true

  def self.digest(string)
    BCrypt::Password.create(string, cost: cost)
  end

  private

  def cost
    return BCrypt::Engine::MIN_COST if ActiveModel::SecurePassword.min_cost
    BCrypt::Engine.cost
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

# Class that controls the whole application
class ApplicationController < ActionController::Base
  before_action :set_locale

  include SessionsHelper

  def set_locale
    cookies[:locale] = params[:lang] if params[:lang].present?
    I18n.locale = cookies[:locale] if cookies[:locale] != ''
  end
end

app/controllers/boards_controller.rb
# frozen_string_literal: true

# Class that controls the board model
class BoardsController < ApplicationController
  def show
    redirect_to log_in_path unless logged_in?
    @board = Board.find(params[:id])
    redirect_to root_path if @board.nil?
    @board.guest = current_user.username unless host?(@board)
    @board.save
  end

  def create
    @board = Board.new(host: current_user.username)
    @board.save
    redirect_to game_path(@board.id)
  end

  def index
    redirect_to log_in_path unless logged_in?
    @boards = Board.where(guest: nil)
  end

  private

  def host?(board)
    current_user.username == board.host
  end
end

app/controllers/sessions_controller.rb
# frozen_string_literal: true

# Class that controls the session from the users
class SessionsController < ApplicationController
  def new
    redirect_to root_path if logged_in?
  end

  def create
    user = User.find_by(username: params[:session][:username])
    if user&.authenticate(params[:session][:password])
      succesful_login(user)
    else
      flash[:error] = error_message(user)
      render 'new'
    end
  end

  def destroy
    log_out if logged_in?
    redirect_to root_url
  end

  private

  def succesful_login(user)
    log_in user
    flash[:success] = t('messages.login_successful')
    redirect_to root_path
  end

  def error_message(user)
    user ? t('messages.incorrect_password') : t('messages.user_unexistant')
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

# Class that controls the user model
class UsersController < ApplicationController
  def new
    redirect_to root_path if logged_in?
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = t('messages.sign_up_succesful')
      redirect_to log_in_path
    else
      render 'new'
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

# Module that provides helper functions
module ApplicationHelper
end

app/helpers/sessions_helper.rb
# frozen_string_literal: true

# Module that provides helper functions focused on sessions
module SessionsHelper
  def log_in(user)
    cookies.signed[:user_id] = user.id
  end

  def current_user
    user_id = cookies.signed[:user_id]
    @current_user ||= User.find(user_id) if user_id
  end

  def logged_in?
    !current_user.nil?
  end

  def log_out
    cookies.delete :user_id
    @current_user = nil
  end
end

app/views/boards/_big_box.slim
.col-sm-4.col-sm-offset-4.big-box
  - for j in 0..2
    .row.m-0
      .col-4.box id=j*3+i
      .col-4.box id=j*3+1+i
      .col-4.box id=j*3+2+i

app/views/boards/_board.slim
tr.row
  th.col-3 = board.host
  th.col-9 = link_to t(:join), game_path(board.id), class: "btn btn-primary btn-block"

app/views/boards/_game.slim
.col-sm-7#board
  - for i in 0..2
    .row
      = render 'big_box', i:i*3*9
      = render 'big_box', i:(i*3+1)*9
      = render 'big_box', i:(i*3+2)*9

app/views/boards/_header.slim
.col-md-12
  h1 Multiplayer
  h2 = t :score
  .d-flex.justify-content-between.row
    .col.text-left.ml-8
      span.xSign.mr-1
        | X =
      span.xScore
        | 0
    .col.text-right.mr-8
      span.oSign.mr-1
        | O =
      span.oScore
        | 0

br
hr

app/views/boards/_nav.slim
header class="navbar navbar-dark navbar-full bg-primary doc-navbar-default"
  button aria-controls="navdrawerDefault" aria-expanded="false" aria-label="Toggle Navdrawer" class="navbar-toggler" data-target="#navdrawerDefault" data-toggle="navdrawer"
    span class="navbar-toggler-icon"
  span class="navbar-brand mr-auto"Tic Tac Toe HL
div aria-hidden="true" class="navdrawer" id="navdrawerDefault" tabindex="-1"
  div class="navdrawer-content"
    div class="navdrawer-header"
      span class="navbar-brand px-0"=current_user.username
    nav class="navdrawer-nav"
      = link_to logout_path, method: :delete,class: "nav-item nav-link active"
        i class="material-icons" exit_to_app
        span =t(:log_out)

app/views/boards/index.slim
= render 'boards/nav'
.card.container.mb-4.mt-4
  table.table
    thead
      tr.row
        th.col-3 = t(:host)
        th.col-8
        th.col-1.mb-3
          = simple_form_for :session do |f|
            = f.button :button, class: 'btn btn-sm btn-float'
              i.material-icons add
    tbody
      = render @boards

app/views/boards/show.slim
=provide(:title, "Game")
.text-center.message-container.mt-4.container
  h1 Multiplayer
  span = t(:waiting)
.text-center.board-container.mt-4.container.mb-4
  .row
    = render 'header'
  .row.d-flex.justify-content-center data-channel="game" data-game-id=@board.id
    = render 'game'
  .row
    .col
      a#reset.btn.btn-danger.btn-block.btn-radius.text-white = t(:surrender)
    .col
      = link_to t(:leave_game), root_path, id:"back", class: "btn btn-danger btn-block btn-radius text-white"

app/views/layouts/_footer.html.slim
footer.row.col-12.d-flex.justify-content-end.m-0.pt-2
  ul
    li = link_to "ES", "#{request.path}?lang=es"
    li = link_to "EN", "#{request.path}?lang=en"

app/views/layouts/_notification.html.erb
<script type="text/javascript"  data-turbolinks-eval="true">
  <% flash.each do |type, message| %>
    <% if message.is_a? Array %>
      <% message.each do |m| %>
        <%= "alertify.#{type}("%> "<%== j m %>" <%= ");" %>
      <% end %>
    <% else %>
        <%= "alertify.#{type}("%> "<%== j message %>" <%= ");" %>
    <% end %>
  <% end %>
</script>

app/views/layouts/application.slim
doctype html
html
  head
    meta name="viewport" content="width=device-width, initial-scale=1"
    meta content=("text/html; charset=UTF-8") http-equiv="Content-Type" /
    title = yield(:title)
    = favicon_link_tag
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'

  body#application data-controller=controller.controller_name data-action=controller.action_name
    = render 'layouts/notification'
    .content
      = yield
    //= render 'layouts/footer'

app/views/shared/_error_messages.slim
 - if object.errors.any?
  div id="error_explanation"
    div class="alert alert-danger"
      span The form contains 
      span = pluralize(object.errors.count, "error")
    ul
      - object.errors.full_messages.each do |msg|
        li = msg

app/views/users/_form.slim
= simple_form_for @user, url: sign_up_path, html: {class: 'form-signin form-inline'} do |f|
  .form-label-group.mb-3
    = f.input :username, input_html: { class: 'form-control' }, class: '', placeholder: t('attributes.username'), label: false
  .form-label-group.mb-3
    = f.input :password, input_html: { class: 'form-control' }, placeholder: t('attributes.password'), label: false
  .form-label-group.mb-3
    = f.input :password_confirmation, input_html: { class: 'form-control' }, placeholder: t('attributes.password_confirmation'), label: false
  = f.button :submit, t('attributes.sign_up'), class: 'btn btn-lg btn-success btn-block'
  = link_to t('attributes.log_in'), log_in_path, class: "btn btn-lg btn-primary btn-block"

app/views/users/new.slim
= provide(:title, "Sign up")
div.application-container
  .row
    h1.h3.mb-3.font-weight-normal = t('attributes.sign_up')
  .container
    = render 'form'